[tool.poetry]
name = "pyra-setup-tool"
version = "1.0.0"
description = ""
authors = [
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Patrick Aigner <patrick.aigner@tum.de>"
]

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.5"

[tool.poetry.group.dev.dependencies]
black = "^22.6.0"
mypy = "^0.971"
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95

[tool.mypy]
strict = true
implicit_reexport = true
no_warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "colorama.*",
]
ignore_missing_imports = true