[tool.poetry]
name = "pyra-setup-tool"
version = "1.0.0"
description = ""
authors = [
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Patrick Aigner <patrick.aigner@tum.de>"
]

[tool.poetry.dependencies]
python = "3.10"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
