name: "test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # check-out repo and set-up python
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install ".[dev]"

      - name: Run Pytests
        run: |
          mkdir ~/Documents
          mkdir ~/Desktop
          pytest --verbose --cov=src tests
          coverage report
