name: "test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # check-out repo and set-up python
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      # load caches (dependencies and poetry binaries)
      - name: Load cached venv
        id: load-cached-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      # install dependencies if venv not cached
      - name: Install Poetry
        if: steps.load-cached-venv.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        if: steps.load-cached-venv.outputs.cache-hit != 'true'
        run: |
          poetry install --with dev

      # run test suite
      - name: Run pytest tests
        run: |
          mkdir ~/Documents
          mkdir ~/Desktop
          source .venv/bin/activate
          pytest --verbose --cov=src tests
          coverage report
